### ISSUE TITLE
Use case(s)

### ISSUE THREAD

**Issue by pedroms** [linsage/gitlab-treeview#1]
First of all, thanks for putting this together! I'm a UX Designer at GitLab, and it's great to see other people improving GitLab.

I'm curious to understand what is the problem that this extension solves for you personally. We've had many requests for an easily accessible file tree. I would like to hear your thoughts on why it's beneficial for your use cases. Thanks in advance 🙇

**Comment by yuankunzhang** [comment]
It helps for easier navigation when walking through the project codes. There has been a Chome extension for Github with the same purpose, called [Octotree](https://chrome.google.com/webstore/detail/octotree/bkhaagjahfmjljalopjnoealnfndnagc?hl=en-US).

**Comment by pedroms** [comment]
Thanks for explaining!
