### ISSUE TITLE
Wrong private token with gitlab 10.x

### ISSUE THREAD

**Issue by STRRL** [linsage/gitlab-treeview#3]
main.js line 27

`var href = "" + $("head link[rel='alternate']").attr("href");`

On gitlab 10.x, here is rss_token instead of private_token.

Delete this param directly was worked, both internal and private project.

It has been tested with gitlab.ynuosa.org.

But i do not know how it works, and im not sure it also works on other site.

Thanks! 😄

**Comment by linsage** [comment]
Thanks,  fixed in 1.3 version
